# Generated by Django 4.2.6 on 2023-12-01 19:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b020695c-896f-489d-920a-05186d0f81e3"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
